# Generated by Django 5.0.4 on 2024-04-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='manufacturing_date',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='reserved_amount',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='rim',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='season',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='speed_index',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='tire_size',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='tire_size_1',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='width',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='zip_code',
        ),
    ]
