# Generated by Django 5.0.4 on 2024-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tire_car_type_tire_code_tire_country_tire_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='reserved_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
