# Generated by Django 5.0.4 on 2024-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservedtire'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
